name: Mirror to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Mirror to GitLab
        run: |
          git push --force --all https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MotalebShabbir/learning-lab.git
          git push --force --tags https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MotalebShabbir/learning-lab.git
